apiVersion: v1
kind: List
metadata: {}
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      image.openshift.io/triggers: '[{"from":{"kind":"ImageStreamTag","name":"pacman:latest","namespace":"$PROJ"},"fieldPath":"spec.template.spec.containers[?(@.name==\"pacman\")].image"}]'
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: pacman
      app.kubernetes.io/component: pacman
      app.kubernetes.io/instance: pacman
    name: pacman
  spec:
    replicas: 1
    selector:
      matchLabels:
        deployment: pacman
    strategy: {}
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
          nodeinfo: '{}'
        creationTimestamp: null
        labels:
          deployment: pacman
      spec:
        containers:
        - image: ' '
          name: pacman
          ports:
          - containerPort: 8080
            protocol: TCP
          volumeMounts:
            - name: nodeinfo
              mountPath: /etc/nodeinfo
          resources: {}
        volumes:
          - name: nodeinfo
            downwardAPI:
              items:
                - path: "data"
                  fieldRef:
                    fieldPath: metadata.annotations['nodeinfo']
  status: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: pacman
      app.kubernetes.io/component: pacman
      app.kubernetes.io/instance: pacman
    name: pacman
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      deployment: pacman
  status:
    loadBalancer: {}
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    annotations:
      openshift.io/host.generated: "true"
    labels:
      app: pacman
      app.kubernetes.io/component: pacman
      app.kubernetes.io/instance: pacman
    name: pacman
  spec:
    port:
      targetPort: 8080-tcp
    to:
      kind: Service
      name: pacman
      weight: 100
    wildcardPolicy: None
  status: {}
